// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUDTFYiEN0I5BTrAOXh-M7F8yyg9dYyoA',
    appId: '1:357340853860:web:7a98d4234faaf86445d171',
    messagingSenderId: '357340853860',
    projectId: 'formcapture',
    authDomain: 'formcapture.firebaseapp.com',
    storageBucket: 'formcapture.appspot.com',
    measurementId: 'G-L2BQSWDCGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzJVuLBHdEAW4XckzbBxcM5_3l18vYnQ',
    appId: '1:357340853860:android:b4cf4e340fb7613e45d171',
    messagingSenderId: '357340853860',
    projectId: 'formcapture',
    storageBucket: 'formcapture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ0F_WKFEX66-r0feEY4N47PTxAwkhssg',
    appId: '1:357340853860:ios:f3223b1e3f9acc0e45d171',
    messagingSenderId: '357340853860',
    projectId: 'formcapture',
    storageBucket: 'formcapture.appspot.com',
    iosClientId: '357340853860-cjcrtfooofd08in8sv8q6bbakauadmb0.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.formcapture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ0F_WKFEX66-r0feEY4N47PTxAwkhssg',
    appId: '1:357340853860:ios:2ee624fb8a39525245d171',
    messagingSenderId: '357340853860',
    projectId: 'formcapture',
    storageBucket: 'formcapture.appspot.com',
    iosClientId: '357340853860-348m3b8ne155656amn1j6ochbijb6usl.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.formcapture.RunnerTests',
  );
}
